import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '🍔 Your title',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="navigation">
          <Link className="navigation-logo" href="/">
            Razer
          </Link>

          <Link className="navigation-link" href="https://www.razer.com/community">
            COMMUNITY
          </Link>
          <Link className="navigation-link" href="https://support.razer.com/?c=us">
            SUPPORT
          </Link>
        </nav>
        <main className="main-container">{children}</main>
        <footer>Created by Galin Ivanov</footer>
      </body>
    </html>
  );
}
